name: Run Ansible Lint
description: Run Ansible Lint
author: Denys Rondaliev <denysrondaliev@gmail.com>

branding:
  icon: "box"
  color: "yellow"

inputs:
  path:
    description: Path to scan
    required: false
    default: "."
  python_version:
    description: Python version
    required: false
    default: "3.*"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      run: "python3 -m pip install ansible-lint"
      shell: bash

    - name: Lint code
      run: "ansible-lint ${{ inputs.path }}"
      shell: bash
